DATA SEGMENT 
ARRAY DB 01H, 02H, 0F2H 
COUNT EQU ($-ARRAY) 
SUM DB 1 DUP(?) 
CARRY DB 1 DUP(?) 
DATA ENDS 
CODE SEGMENT
ASSUME CS: CODE, DS: DATA
START: MOV AX, DATA 
	MOV DS, AX 
	LEA SI, ARRAY 
	MOV AX, 0000H
	MOV CX, COUNT
L1: 	ADD AL, [SI] 
	JNC L2
	INC AH
L2: 	INC SI 
	DEC CX 
	JNZ L1 
	MOV SUM, AL 
	MOV CARRY, AH 
	MOV AH, 4CH 
	INT 21H
CODE ENDS 
END START